### ISSUE TITLE
HERMES : Erreur lors de l'envoi d'un mail - Action : écrire un message vers n-tiers

### ISSUE THREAD

**Issue by Dsniss** [Ousret/hermes#23]
Bonjour @Ousret 

J'ai un automate dans lequel j'utilise l'action "Ecrire un message vers n-tiers ...." afin de pouvoir envoyer un mail vers un destinataire.

Après plusieurs essais je tombe systématiquement sur une erreur que je ne comprends pas (cf. trace de l'erreur ci-dessous). Pour info, en utilisant l'action "transférer un message électronique ...." je n'ai pas le problème pour transférer un message.

```
_**2020-04-06 19:17:09.094 | CRITICAL | hermes_ui.moteur.processus:thread:243 - L'automate 'OK_Envoi invitation au Suivi OP' est en erreur critique, une exception est soulevée: 'catching classes that do not inherit from BaseException is not allowed'
2020-04-06 19:17:09.094 | CRITICAL | hermes_ui.moteur.processus:thread:249 - Informations complémentaires '<class 'TypeError'>', 'processus.py' à la ligne 164.
2020-04-06 19:17:09.096 | CRITICAL | hermes_ui.moteur.processus:thread:253 - Traceback (most recent call last):
  File "/home/itop/hermes/hermes/automate.py", line 1340, in je_realise
    EnvoyerMessageSmtpActionNoeud.ZIP_EXTENSION_SAFEMODE]) is True:
  File "/home/itop/hermes/hermes/automate.py", line 1339, in <listcomp>
    if any([pj_source.nom_fichier.lower().endswith('.' + el) for el in
AttributeError: 'bool' object has no attribute 'nom_fichier'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/itop/hermes/hermes_ui/moteur/processus.py", line 164, in thread
    etat_final_automate = automate.lance_toi(source)
  File "/home/itop/hermes/hermes/automate.py", line 159, in lance_toi
    final_leaf_bool = self._action_racine.je_realise(source) if self._action_racine is not None else False
  File "/home/itop/hermes/hermes/automate.py", line 1909, in je_realise
    return self._jai_reussi(source)
  File "/home/itop/hermes/hermes/automate.py", line 252, in _jai_reussi
    return True and self._noeud_reussite.je_realise(source) if self._noeud_reussite is not None else True
  File "/home/itop/hermes/hermes/automate.py", line 663, in je_realise
    return self._jai_reussi(source, my_payload)
  File "/home/itop/hermes/hermes/automate.py", line 252, in _jai_reussi
    return True and self._noeud_reussite.je_realise(source) if self._noeud_reussite is not None else True
  File "/home/itop/hermes/hermes/automate.py", line 663, in je_realise
    return self._jai_reussi(source, my_payload)
  File "/home/itop/hermes/hermes/automate.py", line 252, in _jai_reussi
    return True and self._noeud_reussite.je_realise(source) if self._noeud_reussite is not None else True
  File "/home/itop/hermes/hermes/automate.py", line 598, in je_realise
    return self._jai_reussi(source, my_payload)
  File "/home/itop/hermes/hermes/automate.py", line 252, in _jai_reussi
    return True and self._noeud_reussite.je_realise(source) if self._noeud_reussite is not None else True
  File "/home/itop/hermes/hermes/automate.py", line 1774, in je_realise
    return self._jai_reussi(source, self._separateur.join(mes_decouvertes))
  File "/home/itop/hermes/hermes/automate.py", line 252, in _jai_reussi
    return True and self._noeud_reussite.je_realise(source) if self._noeud_reussite is not None else True
  File "/home/itop/hermes/hermes/automate.py", line 1215, in je_realise
    return self._jai_reussi(source, str(my_calendar))
  File "/home/itop/hermes/hermes/automate.py", line 252, in _jai_reussi
    return True and self._noeud_reussite.je_realise(source) if self._noeud_reussite is not None else True
  File "/home/itop/hermes/hermes/automate.py", line 1860, in je_realise
    return self._jai_reussi(source)
  File "/home/itop/hermes/hermes/automate.py", line 252, in _jai_reussi
    return True and self._noeud_reussite.je_realise(source) if self._noeud_reussite is not None else True
  File "/home/itop/hermes/hermes/automate.py", line 1373, in je_realise
    except NotImplemented:
TypeError: catching classes that do not inherit from BaseException is not allowed_**_
```

Peux tu m'apporter ton aide STP ?

Merci et bonne journée

Au plaisir d'avoir de tes nouvelles

@Dsniss

**Comment by Ousret** [comment]
Bonjour @Dsniss,

Merci pour le rapport d'erreur.
La trace ci-dessus m'indique que le problème provient d'hermès. J'essaie de proposer un correctif assez rapidement.

**Comment by Ousret** [comment]
Correctif disponible dans la version 1.0.9

**Comment by Dsniss** [comment]
@Ousret 
Je confirme que le problème est corrigé
Bonne journée
@Dsniss
