### ISSUE TITLE
HERMES : Erreur lors de la simulation de détection

### ISSUE THREAD

**Issue by Dsniss** [Ousret/hermes#27]
### **Avec la version 1.09 lorsque je glisse un mail (copié au préalable sur mon bureau ou en provenance d'Outllook) dans la partie simulation de détection j'ai une erreur à l'écran. (cf. mail concerné en PJ) Merci pour ton aide. Bonne journée. @Dsniss 

[NOTIF_VRIFDELAI  Verif si demandes depassent delai et alerter demandeurs.zip](https://github.com/Ousret/hermes/files/4508977/NOTIF_VRIFDELAI.Verif.si.demandes.depassent.delai.et.alerter.demandeurs.zip)

****

Analyse de message
×
ValueError
ValueError: dictionary update sequence element #2 has length 19; 2 is required

Traceback (most recent call last)
File "/home/itop/.local/lib/python3.7/site-packages/flask/app.py", line 2328, in __call__
return self.wsgi_app(environ, start_response)
File "/home/itop/.local/lib/python3.7/site-packages/flask/app.py", line 2314, in wsgi_app
response = self.handle_exception(e)
File "/home/itop/.local/lib/python3.7/site-packages/flask/app.py", line 1760, in handle_exception
reraise(exc_type, exc_value, tb)
File "/home/itop/.local/lib/python3.7/site-packages/flask/_compat.py", line 36, in reraise
raise value
File "/home/itop/.local/lib/python3.7/site-packages/flask/app.py", line 2311, in wsgi_app
response = self.full_dispatch_request()
File "/home/itop/.local/lib/python3.7/site-packages/flask/app.py", line 1834, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/home/itop/.local/lib/python3.7/site-packages/flask/app.py", line 1737, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/home/itop/.local/lib/python3.7/site-packages/flask/_compat.py", line 36, in reraise
raise value
File "/home/itop/.local/lib/python3.7/site-packages/flask/app.py", line 1832, in full_dispatch_request
rv = self.dispatch_request()
File "/home/itop/.local/lib/python3.7/site-packages/flask/app.py", line 1818, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/home/itop/.local/lib/python3.7/site-packages/Flask_Login-0.4.1-py3.7.egg/flask_login/utils.py", line 261, in decorated_view
return func(*args, **kwargs)
File "/home/itop/hermes/hermes_ui/app.py", line 576, in simulation_detecteur_fichier
mon_message = Mail.from_msg(mon_fichier.stream.read())
File "/home/itop/hermes/hermes/mail.py", line 205, in from_msg
'utf-8'
File "/home/itop/hermes/hermes/mail.py", line 190, in from_eml
email.message_from_bytes(eml_content)
File "/home/itop/hermes/hermes/mail.py", line 250, in from_message
el.split('=') for el in [el.lstrip() for el in message_part_header_value.split(';')] if
ValueError: dictionary update sequence element #2 has length 19; 2 is required
This is the Copy/Paste friendly version of the traceback. You can also paste this traceback into a gist: 

Traceback (most recent call last):
  File "/home/itop/.local/lib/python3.7/site-packages/flask/app.py", line 2328, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/itop/.local/lib/python3.7/site-packages/flask/app.py", line 2314, in wsgi_app
    response = self.handle_exception(e)
  File "/home/itop/.local/lib/python3.7/site-packages/flask/app.py", line 1760, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/itop/.local/lib/python3.7/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/home/itop/.local/lib/python3.7/site-packages/flask/app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/itop/.local/lib/python3.7/site-packages/flask/app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/itop/.local/lib/python3.7/site-packages/flask/app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/itop/.local/lib/python3.7/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/home/itop/.local/lib/python3.7/site-packages/flask/app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/itop/.local/lib/python3.7/site-packages/flask/app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/itop/.local/lib/python3.7/site-packages/Flask_Login-0.4.1-py3.7.egg/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/itop/hermes/hermes_ui/app.py", line 576, in simulation_detecteur_fichier
    mon_message = Mail.from_msg(mon_fichier.stream.read())
  File "/home/itop/hermes/hermes/mail.py", line 205, in from_msg
    'utf-8'
  File "/home/itop/hermes/hermes/mail.py", line 190, in from_eml
    email.message_from_bytes(eml_content)
  File "/home/itop/hermes/hermes/mail.py", line 250, in from_message
    el.split('=') for el in [el.lstrip() for el in message_part_header_value.split(';')] if
ValueError: dictionary update sequence element #2 has length 19; 2 is required
The debugger caught an exception in your WSGI application. You can now look at the traceback which led to the error. If you enable JavaScript you can also use additional features such as code execution (if the evalex feature is enabled), automatic pasting of the exceptions and much more.
Brought to you by DON'T PANIC, your friendly Werkzeug powered traceback interpreter

**Comment by Ousret** [comment]
Bonjour @Dsniss 

Un correctif est disponible dans la version 1.0.10, ce problème provenait bien d'hermès. 
**Cette mise à jour va nécessiter que tu lances le script `./upgrade.sh` deux fois. Ceci est important.** J'ai dû rajouter une dépendance externe pour résoudre ce problème.

Bien à toi

**Comment by Dsniss** [comment]
### **Bonjour @Ousret**

### **Après avoir installé la nouvelle version 1.0.10 et fait un essai avec le même mail en entrée, je constate toujours une erreur .**

ValueError
ValueError: string argument should contain only ASCII characters

Traceback (most recent call last)
File "/home/itop/.local/lib/python3.7/site-packages/flask/app.py", line 2328, in __call__
return self.wsgi_app(environ, start_response)
File "/home/itop/.local/lib/python3.7/site-packages/flask/app.py", line 2314, in wsgi_app
response = self.handle_exception(e)
File "/home/itop/.local/lib/python3.7/site-packages/flask/app.py", line 1760, in handle_exception
reraise(exc_type, exc_value, tb)
File "/home/itop/.local/lib/python3.7/site-packages/flask/_compat.py", line 36, in reraise
raise value
File "/home/itop/.local/lib/python3.7/site-packages/flask/app.py", line 2311, in wsgi_app
response = self.full_dispatch_request()
File "/home/itop/.local/lib/python3.7/site-packages/flask/app.py", line 1834, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/home/itop/.local/lib/python3.7/site-packages/flask/app.py", line 1737, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/home/itop/.local/lib/python3.7/site-packages/flask/_compat.py", line 36, in reraise
raise value
File "/home/itop/.local/lib/python3.7/site-packages/flask/app.py", line 1832, in full_dispatch_request
rv = self.dispatch_request()
File "/home/itop/.local/lib/python3.7/site-packages/flask/app.py", line 1818, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/home/itop/.local/lib/python3.7/site-packages/Flask_Login-0.4.1-py3.7.egg/flask_login/utils.py", line 261, in decorated_view
return func(*args, **kwargs)
File "/home/itop/hermes/hermes_ui/app.py", line 576, in simulation_detecteur_fichier
mon_message = Mail.from_msg(mon_fichier.stream.read())
File "/home/itop/hermes/hermes/mail.py", line 203, in from_msg
'utf-8'
File "/home/itop/hermes/hermes/mail.py", line 188, in from_eml
email.message_from_bytes(eml_content)
File "/home/itop/hermes/hermes/mail.py", line 249, in from_message
sub_concerned_body = decodestring(sub_concerned_body).decode(sub_charset_declared if sub_charset_declared else 'utf-8', errors='ignore')
File "/usr/local/lib/python3.7/quopri.py", line 162, in decodestring
return a2b_qp(s, header=header)
ValueError: string argument should contain only ASCII characters
This is the Copy/Paste friendly version of the traceback. You can also paste this traceback into a gist: 

Traceback (most recent call last):
  File "/home/itop/.local/lib/python3.7/site-packages/flask/app.py", line 2328, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/itop/.local/lib/python3.7/site-packages/flask/app.py", line 2314, in wsgi_app
    response = self.handle_exception(e)
  File "/home/itop/.local/lib/python3.7/site-packages/flask/app.py", line 1760, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/itop/.local/lib/python3.7/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/home/itop/.local/lib/python3.7/site-packages/flask/app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/itop/.local/lib/python3.7/site-packages/flask/app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/itop/.local/lib/python3.7/site-packages/flask/app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/itop/.local/lib/python3.7/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/home/itop/.local/lib/python3.7/site-packages/flask/app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/itop/.local/lib/python3.7/site-packages/flask/app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/itop/.local/lib/python3.7/site-packages/Flask_Login-0.4.1-py3.7.egg/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/itop/hermes/hermes_ui/app.py", line 576, in simulation_detecteur_fichier
    mon_message = Mail.from_msg(mon_fichier.stream.read())
  File "/home/itop/hermes/hermes/mail.py", line 203, in from_msg
    'utf-8'
  File "/home/itop/hermes/hermes/mail.py", line 188, in from_eml
    email.message_from_bytes(eml_content)
  File "/home/itop/hermes/hermes/mail.py", line 249, in from_message
    sub_concerned_body = decodestring(sub_concerned_body).decode(sub_charset_declared if sub_charset_declared else 'utf-8', errors='ignore')
  File "/usr/local/lib/python3.7/quopri.py", line 162, in decodestring
    return a2b_qp(s, header=header)
ValueError: string argument should contain only ASCII characters
The debugger caught an exception in your WSGI application. You can now look at the traceback which led to the error. If you enable JavaScript you can also use additional features such as code execution (if the evalex feature is enabled), automatic pasting of the exceptions and much more.

**Comment by Ousret** [comment]
ça doit être bon, relance `./upgrade.sh`

**Comment by Dsniss** [comment]
Bonjour Ahmed,

 

C’est la version 1.0.11 qui est dispo à présent ?

Car :

-          Le upgrade (cf. copie ci-dessous) effectué 3 fois ne semble pas avoir fait de mise à jour

-          Dans le fichier /home/itop/hermes/hermes_ui/template/admin/base.html j’ai toujours la version 1.0.10

-          Et après un test j’ai toujours une erreur (cf. copie en bas de ma réponse)

 


$ ./upgrade.sh

 

Warning: Permanently added '[ssh.github.com]:443,[192.30.253.122]:443' (RSA) to the list of known hosts.

HEAD est maintenant sur 6b80783 :bug: :poop: oupsy, invert if (not) stmt

running install

running bdist_egg

running egg_info

writing hermes.egg-info/PKG-INFO

writing dependency_links to hermes.egg-info/dependency_links.txt

writing requirements to hermes.egg-info/requires.txt

writing top-level names to hermes.egg-info/top_level.txt

reading manifest file 'hermes.egg-info/SOURCES.txt'

writing manifest file 'hermes.egg-info/SOURCES.txt'

installing library code to build/bdist.linux-x86_64/egg

running install_lib

running build_py

creating build/bdist.linux-x86_64/egg

creating build/bdist.linux-x86_64/egg/hermes

copying build/lib/hermes/__init__.py -> build/bdist.linux-x86_64/egg/hermes

copying build/lib/hermes/engine.py -> build/bdist.linux-x86_64/egg/hermes

copying build/lib/hermes/logger.py -> build/bdist.linux-x86_64/egg/hermes

copying build/lib/hermes/i18n.py -> build/bdist.linux-x86_64/egg/hermes

copying build/lib/hermes/analysis.py -> build/bdist.linux-x86_64/egg/hermes

copying build/lib/hermes/automate.py -> build/bdist.linux-x86_64/egg/hermes

copying build/lib/hermes/detecteur.py -> build/bdist.linux-x86_64/egg/hermes

copying build/lib/hermes/session.py -> build/bdist.linux-x86_64/egg/hermes

copying build/lib/hermes/source.py -> build/bdist.linux-x86_64/egg/hermes

copying build/lib/hermes/mail.py -> build/bdist.linux-x86_64/egg/hermes

creating build/bdist.linux-x86_64/egg/hermes_ui

copying build/lib/hermes_ui/__init__.py -> build/bdist.linux-x86_64/egg/hermes_ui

copying build/lib/hermes_ui/flask_extended.py -> build/bdist.linux-x86_64/egg/hermes_ui

copying build/lib/hermes_ui/incident.py -> build/bdist.linux-x86_64/egg/hermes_ui

copying build/lib/hermes_ui/app.py -> build/bdist.linux-x86_64/egg/hermes_ui

creating build/bdist.linux-x86_64/egg/msg_parser

copying build/lib/msg_parser/setup.py -> build/bdist.linux-x86_64/egg/msg_parser

byte-compiling build/bdist.linux-x86_64/egg/hermes/__init__.py to __init__.cpython-37.pyc

byte-compiling build/bdist.linux-x86_64/egg/hermes/engine.py to engine.cpython-37.pyc

byte-compiling build/bdist.linux-x86_64/egg/hermes/logger.py to logger.cpython-37.pyc

byte-compiling build/bdist.linux-x86_64/egg/hermes/i18n.py to i18n.cpython-37.pyc

byte-compiling build/bdist.linux-x86_64/egg/hermes/analysis.py to analysis.cpython-37.pyc

byte-compiling build/bdist.linux-x86_64/egg/hermes/automate.py to automate.cpython-37.pyc

byte-compiling build/bdist.linux-x86_64/egg/hermes/detecteur.py to detecteur.cpython-37.pyc

byte-compiling build/bdist.linux-x86_64/egg/hermes/session.py to session.cpython-37.pyc

byte-compiling build/bdist.linux-x86_64/egg/hermes/source.py to source.cpython-37.pyc

byte-compiling build/bdist.linux-x86_64/egg/hermes/mail.py to mail.cpython-37.pyc

byte-compiling build/bdist.linux-x86_64/egg/hermes_ui/__init__.py to __init__.cpython-37.pyc

byte-compiling build/bdist.linux-x86_64/egg/hermes_ui/flask_extended.py to flask_extended.cpython-37.pyc

byte-compiling build/bdist.linux-x86_64/egg/hermes_ui/incident.py to incident.cpython-37.pyc

byte-compiling build/bdist.linux-x86_64/egg/hermes_ui/app.py to app.cpython-37.pyc

byte-compiling build/bdist.linux-x86_64/egg/msg_parser/setup.py to setup.cpython-37.pyc

creating build/bdist.linux-x86_64/egg/EGG-INFO

copying hermes.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO

copying hermes.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO

copying hermes.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO

copying hermes.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO

copying hermes.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO

zip_safe flag not set; analyzing archive contents...

hermes.__pycache__.automate.cpython-37: module references __path__

hermes.__pycache__.i18n.cpython-37: module references __file__

hermes.__pycache__.logger.cpython-37: module references __file__

hermes.__pycache__.logger.cpython-37: module references __path__

hermes_ui.__pycache__.__init__.cpython-37: module references __path__

hermes_ui.__pycache__.app.cpython-37: module references __file__

hermes_ui.__pycache__.app.cpython-37: module references __path__

msg_parser.__pycache__.setup.cpython-37: module references __file__

creating 'dist/hermes-1.0.10-py3.7.egg' and adding 'build/bdist.linux-x86_64/egg' to it

removing 'build/bdist.linux-x86_64/egg' (and everything under it)

Processing hermes-1.0.10-py3.7.egg

removing '/home/itop/.local/lib/python3.7/site-packages/hermes-1.0.10-py3.7.egg' (and everything under it)

creating /home/itop/.local/lib/python3.7/site-packages/hermes-1.0.10-py3.7.egg

Extracting hermes-1.0.10-py3.7.egg to /home/itop/.local/lib/python3.7/site-packages

hermes 1.0.10 is already the active version in easy-install.pth

 

Installed /home/itop/.local/lib/python3.7/site-packages/hermes-1.0.10-py3.7.egg

Processing dependencies for hermes==1.0.10

Searching for emails>=0.6.1

Reading https://pypi.org/simple/emails/

No local packages or working download links found for emails>=0.6.1

error: Could not find suitable distribution for Requirement.parse('emails>=0.6.1')

2020-04-23 08:40:54.041 | INFO     | hermes_ui:<module>:5 - Chargement du dossiers contenant les configurations YAML

2020-04-23 08:40:54.042 | INFO     | hermes_ui:<module>:7 - Les fichiers de configuration suivant ont été chargées: "[]"

INFO  [alembic.runtime.migration] Context impl SQLiteImpl.

INFO  [alembic.runtime.migration] Will assume non-transactional DDL.

yarn run v1.21.1

$ node_modules/.bin/webpack --config webpack.config.js --mode production

Browserslist: caniuse-lite is outdated. Please run next command `yarn upgrade`

Hash: 235d0f2bb6ab034cd082

Version: webpack 4.41.2

Time: 11128ms

Built at: 2020-04-23 08:41:07

                                             Asset       Size  Chunks                                Chunk Names

              7799dece2c79854f63f09e7dfa528b88.jpg    121 KiB          [emitted]

                                           app.css    426 KiB       0  [emitted]              [big]  app

                                    app_hermes.css    189 KiB       2  [emitted]                     app_hermes

             fonts/fontawesome-webfont.674f50d.eot    162 KiB          [emitted]

             fonts/fontawesome-webfont.912ec66.svg    434 KiB          [emitted]              [big]

           fonts/fontawesome-webfont.af7ae50.woff2   75.4 KiB          [emitted]

             fonts/fontawesome-webfont.b06871f.ttf    162 KiB          [emitted]

            fonts/fontawesome-webfont.fee66e7.woff   95.7 KiB          [emitted]

  fonts/glyphicons-halflings-regular.448c34a.woff2   17.6 KiB          [emitted]

    fonts/glyphicons-halflings-regular.8988968.svg    106 KiB          [emitted]

    fonts/glyphicons-halflings-regular.e18bbf6.ttf   44.3 KiB          [emitted]

    fonts/glyphicons-halflings-regular.f4769f9.eot   19.7 KiB          [emitted]

   fonts/glyphicons-halflings-regular.fa27723.woff   22.9 KiB          [emitted]

                fonts/jsoneditor-icons.2b9b487.svg   30.7 KiB          [emitted]

       fonts/titilliumweb-bold-webfont.5053fda.svg    132 KiB          [emitted]

       fonts/titilliumweb-bold-webfont.6378f82.eot   23.5 KiB          [emitted]

       fonts/titilliumweb-bold-webfont.835e1e8.ttf   48.8 KiB          [emitted]

      fonts/titilliumweb-bold-webfont.a00c9ff.woff   26.7 KiB          [emitted]

fonts/titilliumweb-extralight-webfont.1d62466.eot   23.5 KiB          [emitted]

fonts/titilliumweb-extralight-webfont.5214411.svg    137 KiB          [emitted]

fonts/titilliumweb-extralight-webfont.70f1d17.ttf     49 KiB          [emitted]

fonts/titilliumweb-extralight-webfont.7d622d0.woff   26.5 KiB          [emitted]

    fonts/titilliumweb-regular-webfont.3e38950.svg    147 KiB          [emitted]

    fonts/titilliumweb-regular-webfont.4027c77.ttf   49.6 KiB          [emitted]

    fonts/titilliumweb-regular-webfont.6f3bc63.eot   24.5 KiB          [emitted]

   fonts/titilliumweb-regular-webfont.9a3edaa.woff   27.5 KiB          [emitted]

                    js/app.ef6eefd8bdad628cdd86.js   2.36 MiB       0  [emitted] [immutable]  [big]  app

            js/app.ef6eefd8bdad628cdd86.js.LICENSE   6.38 KiB          [emitted]

               js/app_help.51a85487671c28694fae.js   91.5 KiB       1  [emitted] [immutable]         app_help

       js/app_help.51a85487671c28694fae.js.LICENSE  471 bytes          [emitted]

             js/app_hermes.ba884c87f6c7fde9b64a.js   1.72 MiB       2  [emitted] [immutable]  [big]  app_hermes

     js/app_hermes.ba884c87f6c7fde9b64a.js.LICENSE   6.27 KiB          [emitted]

                                     manifest.json   1.01 KiB          [emitted]

Entrypoint app [big] = app.css js/app.ef6eefd8bdad628cdd86.js

Entrypoint app_help = js/app_help.51a85487671c28694fae.js

Entrypoint app_hermes [big] = app_hermes.css js/app_hermes.ba884c87f6c7fde9b64a.js

[133] ../node_modules/moment/locale sync ^\.\/.*$ 3 KiB {0} {2} [optional] [built]

[134] ./scripts/Compoments/hermes_ui.js 35.9 KiB {0} {2} [built]

[140] ./styles/jstree/proton/style.css 39 bytes {0} {2} [built]

[144] ./scripts/app.js 4.86 KiB {0} [built]

[348] ./scripts/Compoments/jquery.a-tools.js 19 KiB {0} [built]

[349] ./scripts/Compoments/jquery.asuggest.js 6.81 KiB {0} [built]

[360] ./styles/hermes-surcharge.css 39 bytes {0} [built]

[361] ./scripts/app_help.js 5.45 KiB {1} [built]

[362] ./scripts/app_hermes.js 9.43 KiB {2} [built]

    + 389 hidden modules

 

WARNING in asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).

This can impact web performance.

Assets:

  fonts/fontawesome-webfont.912ec66.svg (434 KiB)

  app.css (426 KiB)

  js/app.ef6eefd8bdad628cdd86.js (2.36 MiB)

  js/app_hermes.ba884c87f6c7fde9b64a.js (1.72 MiB)

 

WARNING in entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.

Entrypoints:

  app (2.78 MiB)

      app.css

      js/app.ef6eefd8bdad628cdd86.js

  app_hermes (1.91 MiB)

      app_hermes.css

      js/app_hermes.ba884c87f6c7fde9b64a.js

 

 

WARNING in webpack performance recommendations:

You can limit the size of your bundles by using import() or require.ensure to lazy load some parts of your application.

For more info visit https://webpack.js.org/guides/code-splitting/

Child mini-css-extract-plugin ../node_modules/css-loader/dist/cjs.js!styles/hermes-surcharge.css:

    Entrypoint mini-css-extract-plugin = *

    [0] ../node_modules/css-loader/dist/cjs.js!./styles/hermes-surcharge.css 7.95 KiB {0} [built]

        + 1 hidden module

Child mini-css-extract-plugin ../node_modules/css-loader/dist/cjs.js!styles/jstree/proton/style.css:

    Entrypoint mini-css-extract-plugin = *

     [0] ./styles/jstree/proton/fonts/titillium/titilliumweb-extralight-webfont.eot 78 bytes {0} [built]

     [1] ./styles/jstree/proton/fonts/titillium/titilliumweb-regular-webfont.eot 75 bytes {0} [built]

     [2] ./styles/jstree/proton/fonts/titillium/titilliumweb-bold-webfont.eot 72 bytes {0} [built]

     [3] ../node_modules/css-loader/dist/cjs.js!./styles/jstree/proton/style.css 35 KiB {0} [built]

     [6] ./styles/jstree/proton/32px.png 4.38 KiB {0} [built]

     [7] ./styles/jstree/proton/throbber.gif 2.28 KiB {0} [built]

     [8] ./styles/jstree/proton/30px.png 8.4 KiB {0} [built]

     [9] ./styles/jstree/proton/fonts/titillium/titilliumweb-extralight-webfont.woff 79 bytes {0} [built]

    [10] ./styles/jstree/proton/fonts/titillium/titilliumweb-extralight-webfont.ttf 78 bytes {0} [built]

    [11] ./styles/jstree/proton/fonts/titillium/titilliumweb-extralight-webfont.svg 78 bytes {0} [built]

    [12] ./styles/jstree/proton/fonts/titillium/titilliumweb-regular-webfont.woff 76 bytes {0} [built]

    [13] ./styles/jstree/proton/fonts/titillium/titilliumweb-regular-webfont.ttf 75 bytes {0} [built]

    [14] ./styles/jstree/proton/fonts/titillium/titilliumweb-regular-webfont.svg 75 bytes {0} [built]

    [15] ./styles/jstree/proton/fonts/titillium/titilliumweb-bold-webfont.woff 73 bytes {0} [built]

    [16] ./styles/jstree/proton/fonts/titillium/titilliumweb-bold-webfont.ttf 72 bytes {0} [built]

        + 3 hidden modules

Child mini-css-extract-plugin ../node_modules/css-loader/dist/cjs.js!../node_modules/admin-lte/dist/css/AdminLTE.css:

    Entrypoint mini-css-extract-plugin = *

       4 modules

Child mini-css-extract-plugin ../node_modules/css-loader/dist/cjs.js!../node_modules/admin-lte/dist/css/skins/skin-green-light.css:

    Entrypoint mini-css-extract-plugin = *

       2 modules

Child mini-css-extract-plugin ../node_modules/css-loader/dist/cjs.js!../node_modules/awesomplete/awesomplete.css:

    Entrypoint mini-css-extract-plugin = *

       2 modules

Child mini-css-extract-plugin ../node_modules/css-loader/dist/cjs.js!../node_modules/bootstrap/dist/css/bootstrap.css:

    Entrypoint mini-css-extract-plugin = *

       8 modules

Child mini-css-extract-plugin ../node_modules/css-loader/dist/cjs.js!../node_modules/datatables.net-bs/css/dataTables.bootstrap.css:

    Entrypoint mini-css-extract-plugin = *

       2 modules

Child mini-css-extract-plugin ../node_modules/css-loader/dist/cjs.js!../node_modules/dropzone/dist/dropzone.css:

    Entrypoint mini-css-extract-plugin = *

       2 modules

Child mini-css-extract-plugin ../node_modules/css-loader/dist/cjs.js!../node_modules/font-awesome/css/font-awesome.css:

    Entrypoint mini-css-extract-plugin = *

       9 modules

Child mini-css-extract-plugin ../node_modules/css-loader/dist/cjs.js!../node_modules/highlight.js/styles/atelier-lakeside-dark.css:

    Entrypoint mini-css-extract-plugin = *

       2 modules

Child mini-css-extract-plugin ../node_modules/css-loader/dist/cjs.js!../node_modules/intro.js/introjs.css:

    Entrypoint mini-css-extract-plugin = *

       2 modules

Child mini-css-extract-plugin ../node_modules/css-loader/dist/cjs.js!../node_modules/intro.js/themes/introjs-modern.css:

    Entrypoint mini-css-extract-plugin = *

       2 modules

Child mini-css-extract-plugin ../node_modules/css-loader/dist/cjs.js!../node_modules/jquery.terminal/css/jquery.terminal.css:

    Entrypoint mini-css-extract-plugin = *

       2 modules

Child mini-css-extract-plugin ../node_modules/css-loader/dist/cjs.js!../node_modules/jsoneditor/dist/jsoneditor.css:

    Entrypoint mini-css-extract-plugin = *

       4 modules

Child mini-css-extract-plugin ../node_modules/css-loader/dist/cjs.js!../node_modules/select2/dist/css/select2.css:

    Entrypoint mini-css-extract-plugin = *

       2 modules

Done in 12.63s.

 

 

 

Erreur lors du traitement du fichier

 


ValueError

ValueError: string argument should contain only ASCII characters

 

Traceback (most recent call last)

File "/home/itop/.local/lib/python3.7/site-packages/flask/app.py", line 2328, in __call__

return self.wsgi_app(environ, start_response)

File "/home/itop/.local/lib/python3.7/site-packages/flask/app.py", line 2314, in wsgi_app

response = self.handle_exception(e)

File "/home/itop/.local/lib/python3.7/site-packages/flask/app.py", line 1760, in handle_exception

reraise(exc_type, exc_value, tb)

File "/home/itop/.local/lib/python3.7/site-packages/flask/_compat.py", line 36, in reraise

raise value

File "/home/itop/.local/lib/python3.7/site-packages/flask/app.py", line 2311, in wsgi_app

response = self.full_dispatch_request()

File "/home/itop/.local/lib/python3.7/site-packages/flask/app.py", line 1834, in full_dispatch_request

rv = self.handle_user_exception(e)

File "/home/itop/.local/lib/python3.7/site-packages/flask/app.py", line 1737, in handle_user_exception

reraise(exc_type, exc_value, tb)

File "/home/itop/.local/lib/python3.7/site-packages/flask/_compat.py", line 36, in reraise

raise value

File "/home/itop/.local/lib/python3.7/site-packages/flask/app.py", line 1832, in full_dispatch_request

rv = self.dispatch_request()

File "/home/itop/.local/lib/python3.7/site-packages/flask/app.py", line 1818, in dispatch_request

return self.view_functions[rule.endpoint](**req.view_args)

File "/home/itop/.local/lib/python3.7/site-packages/Flask_Login-0.4.1-py3.7.egg/flask_login/utils.py", line 261, in decorated_view

return func(*args, **kwargs)

File "/home/itop/hermes/hermes_ui/app.py", line 576, in simulation_detecteur_fichier

mon_message = Mail.from_msg(mon_fichier.stream.read())

File "/home/itop/hermes/hermes/mail.py", line 203, in from_msg

'utf-8'

File "/home/itop/hermes/hermes/mail.py", line 188, in from_eml

email.message_from_bytes(eml_content)

File "/home/itop/hermes/hermes/mail.py", line 264, in from_message

concerned_body = decodestring(concerned_body).decode(charset_declared if charset_declared else 'utf-8', errors='ignore')

File "/usr/local/lib/python3.7/quopri.py", line 162, in decodestring

return a2b_qp(s, header=header)

ValueError: string argument should contain only ASCII characters

This is the Copy/Paste friendly version of the traceback. You can also paste this traceback into a gist: 

 

Traceback (most recent call last):

  File "/home/itop/.local/lib/python3.7/site-packages/flask/app.py", line 2328, in __call__

    return self.wsgi_app(environ, start_response)

  File "/home/itop/.local/lib/python3.7/site-packages/flask/app.py", line 2314, in wsgi_app

    response = self.handle_exception(e)

  File "/home/itop/.local/lib/python3.7/site-packages/flask/app.py", line 1760, in handle_exception

    reraise(exc_type, exc_value, tb)

  File "/home/itop/.local/lib/python3.7/site-packages/flask/_compat.py", line 36, in reraise

    raise value

  File "/home/itop/.local/lib/python3.7/site-packages/flask/app.py", line 2311, in wsgi_app

    response = self.full_dispatch_request()

  File "/home/itop/.local/lib/python3.7/site-packages/flask/app.py", line 1834, in full_dispatch_request

    rv = self.handle_user_exception(e)

  File "/home/itop/.local/lib/python3.7/site-packages/flask/app.py", line 1737, in handle_user_exception

    reraise(exc_type, exc_value, tb)

  File "/home/itop/.local/lib/python3.7/site-packages/flask/_compat.py", line 36, in reraise

    raise value

  File "/home/itop/.local/lib/python3.7/site-packages/flask/app.py", line 1832, in full_dispatch_request

    rv = self.dispatch_request()

  File "/home/itop/.local/lib/python3.7/site-packages/flask/app.py", line 1818, in dispatch_request

    return self.view_functions[rule.endpoint](**req.view_args)

  File "/home/itop/.local/lib/python3.7/site-packages/Flask_Login-0.4.1-py3.7.egg/flask_login/utils.py", line 261, in decorated_view

    return func(*args, **kwargs)

  File "/home/itop/hermes/hermes_ui/app.py", line 576, in simulation_detecteur_fichier

    mon_message = Mail.from_msg(mon_fichier.stream.read())

  File "/home/itop/hermes/hermes/mail.py", line 203, in from_msg

    'utf-8'

  File "/home/itop/hermes/hermes/mail.py", line 188, in from_eml

    email.message_from_bytes(eml_content)

  File "/home/itop/hermes/hermes/mail.py", line 264, in from_message

    concerned_body = decodestring(concerned_body).decode(charset_declared if charset_declared else 'utf-8', errors='ignore')

  File "/usr/local/lib/python3.7/quopri.py", line 162, in decodestring

    return a2b_qp(s, header=header)

ValueError: string argument should contain only ASCII characters

The debugger caught an exception in your WSGI application. You can now look at the traceback which led to the error. If you enable JavaScript you can also use additional features such as code execution (if the evalex feature is enabled), automatic pasting of the exceptions and much more.

 

Il y a-t-il une manip particulière que je n’aurais pas effectuée ?

 

Merci et bonne journée Ahmed

 

Denis

 

 

De : TAHRI Ahmed R. [mailto:notifications@github.com] 
Envoyé : mercredi 22 avril 2020 23:31
À : Ousret/hermes
Cc : Dsniss; Mention
Objet : Re: [Ousret/hermes] HERMES : Erreur lors de la simulation de détection (#27)

 

ça doit être bon, relance ./upgrade.sh

**Comment by Ousret** [comment]
Bonjour,

Pour la version qui ne s'actualise pas dans l'IHM c'est normal, j'ai fait
ça dans l'urgence.
As-tu essayé de redémarrer le service ? Normalement ce problème doit
disparaître.

Merci

**Comment by Dsniss** [comment]
Ok pas de soucis avec le numéro de version, j’ai compris J

 

Sinon j’ai redémarré le service et fais un essai et j’obtiens le message suivant lors de la simulation détection

Bien évidemment c’est avec l’exemple de mail que j’avais ajouté à ma demande.

 

Si je fais l’essai avec plusieurs mails différents  j’ai très très peu de réussite et pour les cas en échec c’est toujours le message ci-joint

Description : cid:image001.png@01D6198E.0E1F21A0

 

Bonne fin de journée Ahmed et encore merci J

 

Denis

 

De : TAHRI Ahmed R. [mailto:notifications@github.com] 
Envoyé : jeudi 23 avril 2020 09:28
À : Ousret/hermes
Cc : Dsniss; Mention
Objet : Re: [Ousret/hermes] HERMES : Erreur lors de la simulation de détection (#27)

 

Bonjour,

Pour la version qui ne s'actualise pas dans l'IHM c'est normal, j'ai fait
ça dans l'urgence.
As-tu essayé de redémarrer le service ? Normalement ce problème doit
disparaître.

Merci
