### ISSUE TITLE
HERMES : Nouvelle erreur lors du traitement d'un mail (1)

### ISSUE THREAD

**Issue by Dsniss** [Ousret/hermes#30]
### Je constate une nouvelle erreur lors du traitement d'un mail qui bloque le traitement des autres messages

2020-04-30 07:58:14.127 | DEBUG    | hermes_ui.moteur.processus:thread:75 - 1 usine(s) à production de source sont actives
2020-04-30 07:58:14.209 | DEBUG    | hermes_ui.moteur.processus:thread:89 - 16 automates en production sont actifs
2020-04-30 07:58:14.209 | DEBUG    | hermes_ui.moteur.processus:thread:93 - Ouverture de la BAL 'demandes-gie'@'cas-mail'
172.17.25.42 - - [30/Apr/2020 07:58:14] "GET /admin/rest/logger?offset=2335 HTTP/1.1" 200 -
Exception in thread Thread-40:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/home/itop/hermes/hermes_ui/moteur/processus.py", line 100, in thread
    sources = mail_factory.extraire()
  File "/home/itop/hermes/hermes/mail.py", line 522, in extraire
    mail = Mail.from_message(email_message)
  File "/home/itop/hermes/hermes/mail.py", line 270, in from_message
    concerned_body if content_transfert_encoding_declared is not None and 'quoted-printable' not in content_transfert_encoding_declared else decodestring(concerned_body).decode(charset_declared if charset_declared is not None else 'utf-8', errors='ignore')
  File "/usr/local/lib/python3.7/quopri.py", line 162, in decodestring
    return a2b_qp(s, header=header)
ValueError: string argument should contain only ASCII characters

### Merci pour ton aide (en PJ l'exemple de message)

[Exemple.zip](https://github.com/Ousret/hermes/files/4556389/Exemple.zip)

**Comment by Dsniss** [comment]
Petite précision identique aux précédentes.
Le fait de copier le mail sur mon bureau Windows et de le redéposer dans le répertoire (inbox) de traitement permet à HERMES de traiter le mail sans erreur !!!

**Comment by Ousret** [comment]
Corrigé dans 1.0.13 @Dsniss

**Comment by Dsniss** [comment]
@Ousret 
Parfait c'est nickel et fonctionne
Merci
@Dsniss

**Comment by Ousret** [comment]
Avec plaisir.
