### ISSUE TITLE
Files missing after docker build

### ISSUE THREAD

**Issue by dutch2005** [Ousret/hermes#49]
**E:\ousret-hermes>docker run af24c862a3db**
Traceback (most recent call last):
  File "wsgi.py", line 2, in <module>
    from hermes_ui.app import app
  File "/app/hermes_ui/__init__.py", line 1, in <module>
    from .app import app
  File "/app/hermes_ui/app.py", line 48, in <module>
    app.config.from_yaml(join(app.root_path, '../configuration.yml'))
  File "/app/hermes_ui/flask_extended.py", line 15, in from_yaml
    c = yaml.load(f, Loader=yaml.FullLoader)
  File "/usr/local/lib/python3.8/site-packages/PyYAML-5.3.1-py3.8-linux-x86_64.egg/yaml/__init__.py", line 114, in load
    return loader.get_single_data()
  File "/usr/local/lib/python3.8/site-packages/PyYAML-5.3.1-py3.8-linux-x86_64.egg/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "/usr/local/lib/python3.8/site-packages/PyYAML-5.3.1-py3.8-linux-x86_64.egg/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/usr/local/lib/python3.8/site-packages/PyYAML-5.3.1-py3.8-linux-x86_64.egg/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/usr/local/lib/python3.8/site-packages/PyYAML-5.3.1-py3.8-linux-x86_64.egg/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/local/lib/python3.8/site-packages/PyYAML-5.3.1-py3.8-linux-x86_64.egg/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/usr/local/lib/python3.8/site-packages/PyYAML-5.3.1-py3.8-linux-x86_64.egg/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/local/lib/python3.8/site-packages/PyYAML-5.3.1-py3.8-linux-x86_64.egg/yaml/composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "/usr/local/lib/python3.8/site-packages/PyYAML-5.3.1-py3.8-linux-x86_64.egg/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/usr/local/lib/python3.8/site-packages/PyYAML-5.3.1-py3.8-linux-x86_64.egg/yaml/parser.py", line 428, in parse_block_mapping_key
    if self.check_token(KeyToken):
  File "/usr/local/lib/python3.8/site-packages/PyYAML-5.3.1-py3.8-linux-x86_64.egg/yaml/scanner.py", line 115, in check_token
    while self.need_more_tokens():
  File "/usr/local/lib/python3.8/site-packages/PyYAML-5.3.1-py3.8-linux-x86_64.egg/yaml/scanner.py", line 152, in need_more_tokens
    self.stale_possible_simple_keys()
  File "/usr/local/lib/python3.8/site-packages/PyYAML-5.3.1-py3.8-linux-x86_64.egg/yaml/scanner.py", line 291, in stale_possible_simple_keys
    **raise ScannerError("while scanning a simple key", key.mark,
yaml.scanner.ScannerError: while scanning a simple key
  in "/app/hermes_ui/../configuration.yml", line 8, column 3
could not find expected ':'
  in "/app/hermes_ui/../configuration.yml", line 9, column 3**

**Comment by dutch2005** [comment]
must have been an error on my end, pulling a new file works just fine.
